name: GO Web APP

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o main .

      - name: Test
        run: go test ./...

      - name: Docker Build
        run: docker build -t go-web-app .

      - name: Docker Push
        run: docker push go-web-app
